### PR TITLE
Fixing isNotify() result

### PR DESCRIPTION
**Pull request by artptr**
Should this condition be inverted?

### CODE REVIEW

**Comment by MollsReis** [comment]
This is correct as-is.

[From the JSON-RPC 2.0 SPEC](http://www.jsonrpc.org/specification#notification)

> A Notification is a Request object without an "id" member.

**Comment by artptr** [comment]
Oh, yes, you are right. It was just a problem with client library, that starts count 'id' from 0: https://github.com/gimmi/jsonrpcjs/blob/master/src/jsonrpc.JsonRpc.js#L38

**Comment by MollsReis** [comment]
Now that is a separate fixable issue. That piece of code should probably use isset() or === null instead of just !

**Comment by MollsReis** [comment]
Just opened issue #25 to address this

**Pull request closed without merging**
